# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Home
name: Urs Reupke
email: ursreupke@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Politics, Policy, Language & Leadership.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://reupke.online" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  urskr
linkedin_username: urs-reupke
# youtube_username: UrsReupke

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

site-locale: de-DE
search: true
lunr:
  search_within_pages: true

include: ["_pages"]

footer:
  links:
    - label: "Imprint"
      icon: "fa-solid fa-file-contract"
      url: "/impressum"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://linkedin.com/in/urs-reupke"
    - label: "Steam"
      icon: "fa-brands fa-steam"
      url: "https://steamcommunity.com/id/urskr"
    - label: "Work"
      icon: "fa fa-briefcase"
      url: "https://it-agile.de/urs"
    - label: "Privacy"
      icon: "fa-solid fa-shield"
      url: "/privacy"

defaults:
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: single
      author: "Urs"
      author_profile: true
      tagline: "" #else posts show their first line as tagline
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author: "Urs"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
